northwind:
  target: dev 
  outputs:
    dev:
      # account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID') }}"
      account: de63389.ca-central-1.aws
      database: warehouse_northwind      
      # user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      # password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      user: alissacheng
      password: dYdkuz-mupta4-qyjbaq
      role: accountadmin
      schema: raw
      threads: 12
      type: snowflake
      warehouse: xsmall_wh
      lient_session_keep_alive: False
      