northwind:
  target: dev 
  outputs:
    dev:
      account: nub74122.us-east-1
      database: warehouse_northwind      
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      role: accountadmin
      schema: raw
      threads: 12
      type: snowflake
      warehouse: xsmall_wh
      lient_session_keep_alive: False
